;/*FB_PKG_DELIM*/

__d("CometExternalShareTracking",["isSSR"],(function(t,n,r,o,a,i,l){"use strict";var e="https://wa.me",s="text";function u(t){if(t!=null&&!r("isSSR")){var n=new URL(e);return n.searchParams.append(s,t),n.toString()}}l.getWhatsAppShareURL=u}),98);
__d("CometFriendsFeedResharesDialogQuery$Parameters",["CometFriendsFeedResharesDialogQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometFriendsFeedResharesDialogQuery_facebookRelayOperation"),metadata:{},name:"CometFriendsFeedResharesDialogQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometFriendsFeedResharesDialog.entrypoint",["CometFriendsFeedResharesDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.showEndAddOnChevron,r=e===void 0?!0:e,a=t.storyData,i=t.url;return{extraProps:{showEndAddOnChevron:r,storyData:a,url:i},queries:{resharesQueryReference:{parameters:n("CometFriendsFeedResharesDialogQuery$Parameters"),variables:{scale:o("WebPixelRatio").get(),url:i}}}}},root:r("JSResourceForInteraction")("CometFriendsFeedResharesDialog.react").__setRef("CometFriendsFeedResharesDialog.entrypoint")};l.default=e}),98);
__d("ExternalShareTrackingEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1743606"),s=o("FalcoLoggerInternal").create("external_share_tracking_event",e),u=s;l.default=u}),98);
__d("ShareMenuTypedLoggerLite",["generateLiteTypedLogger"],(function(t,n,r,o,a,i){"use strict";a.exports=n("generateLiteTypedLogger")("logger:ShareMenuLoggerConfig")}),null);
__d("calculateShareSignificance",[],(function(t,n,r,o,a,i){"use strict";var e=5,l=function(n){if(n==null||n==="")return"no_text";var t=new Set;return n.toLowerCase().split(" ").forEach(function(e){return t.add(e)}),t.size>e?"significant":"not_significant"},s=l;i.default=s}),66);
__d("getShareAudienceFromPrivacyString",[],(function(t,n,r,o,a,i){"use strict";var e=function(t){switch(t){case null:case void 0:case"unknown":return"unknown";case"286958161406148":return"self";case"300645083384735":return"everyone";case"368493386561757":case"275425949243301":return"fof";case"123780391104836":case"291667064279714":return"friends";default:return"custom"}},l=e;i.default=l}),66);
__d("ShareMetricsLoggingController",["ShareMenuTypedLoggerLite","calculateShareSignificance","getShareAudienceFromPrivacyString"],(function(t,n,r,o,a,i,l){"use strict";var e=["fb_feed_location"],s={appid:0x7e36f3fcc43bc,name:"feed_share_action"};function u(e){if(e){var t="unknown";e.audience==="own"?t=e.privacy:e==="friend"?t="friend_timeline":t=e.audience;var n=e.add_to_story?"add_to_story_now":"share_now";f("share_created",n,t,"no_text")}}function c(e){if(e){var t=e.responseURL&&e.responseURL.includes("add_to_story")?"add_to_story_now":"share_now";f("share_failure",t,null,"no_text")}}function d(e,t,n,o,a){var i="unknown";switch(t){case"self":i=r("getShareAudienceFromPrivacyString")(a);break;case"friend":i="friend_timeline";break;case"message":i="messenger";break;case"group":i="group";break;case"page":i="page";break}var l;switch(o){case"share_now_menu/share_to_page":l="share_to_page";break;case"share_now_menu/post_to_group":l="share_to_group";break;case"share_now_menu/send_message":l="send_in_message";break;case"share_now_menu/share_friend_timeline":l="share_to_friend_timeline";break;case"share_now_menu/write_post":l="write_post";break;case"share_now_menu/add_to_story":l="add_to_story";break;case"living_room_sprout":l="start_living_room";break;default:l="unknown";break}var s=r("calculateShareSignificance")(n);f(e,l,i,s)}function m(e,t){r("ShareMenuTypedLoggerLite").log(babelHelpers.extends({},s,{fb_share_type:"share_flow_started",shareable_id:e}))}function p(e,t){r("ShareMenuTypedLoggerLite").log(babelHelpers.extends({},s,{fb_share_type:"share_abandoned",shareable_id:e}))}function _(t){var n=t.fb_feed_location,o=babelHelpers.objectWithoutPropertiesLoose(t,e);r("ShareMenuTypedLoggerLite").log(babelHelpers.extends({},s,o))}function f(e,t,n,o){r("ShareMenuTypedLoggerLite").log({fb_share_type:e,fb_entry_point:t,fb_audience:n,fb_significance:o,name:"feed_share_action"})}l.logShareNowResponsePayload=u,l.logShareNowFailure=c,l.logReactComposerEvent=d,l.logShareFlowStarted=m,l.logShareFlowAbandoned=p,l.logShareFunnelEvent=_,l.log=f}),98);
__d("copiedLinkPushToast",["fbt","FBNucleusCheckmarkCircleFilled20Icon.react","FDSIcon.react","cometPushToast","react"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react"));function c(){o("cometPushToast").cometPushToast({icon:u.jsx(r("FDSIcon.react"),{color:"positive",icon:r("FBNucleusCheckmarkCircleFilled20Icon.react"),size:20}),message:s._(/*BTDS*/"Link copied"),testid:"CometCopyLinkToast"},void 0)}l.default=c}),226);
__d("useCometResharesCanSummarize_link_preview.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useCometResharesCanSummarize_link_preview",selections:[{alias:null,args:[{kind:"Literal",name:"supported",value:"C8Y52"}],concreteType:null,kind:"LinkedField",name:"summary_renderer",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],storageKey:'summary_renderer(supported:"C8Y52")'}],type:"LinkPreviewRoot",abstractKey:null};a.exports=e}),null);
__d("useCometResharesCanSummarize",["CometRelay","useCometResharesCanSummarize_link_preview.graphql"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t){var r,a=t.linkPreview,i=o("CometRelay").useFragment(e!==void 0?e:e=n("useCometResharesCanSummarize_link_preview.graphql"),a);return((r=i.summary_renderer)==null?void 0:r.__typename)!=null}l.default=s}),98);