-- Applied to production through the linked Supabase CLI on 2026-08-06.
create table if not exists bpe_chat_conversations (id uuid primary key default gen_random_uuid(), actor_scope text not null, scope_key text not null default 'portfolio', workspace_id uuid references bpe_workspaces(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (actor_scope, scope_key));
create table if not exists bpe_chat_messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references bpe_chat_conversations(id) on delete cascade, role text not null check (role in ('user','assistant','system')), agent text check (agent in ('wendy','ellie')), content text not null check (char_length(content) between 1 and 30000), created_at timestamptz not null default now());
create index if not exists bpe_chat_messages_conversation_created_idx on bpe_chat_messages (conversation_id, created_at);
create table if not exists bpe_chat_action_proposals (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references bpe_chat_conversations(id) on delete cascade, message_id uuid references bpe_chat_messages(id) on delete set null, agent text not null check (agent in ('wendy','ellie')), kind text not null check (kind in ('task_change','build','external','other')), risk text not null check (risk in ('low','medium','high')), summary text not null, details jsonb not null default '{}'::jsonb, status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')), approved_at timestamptz, created_at timestamptz not null default now());
create index if not exists bpe_chat_action_proposals_conversation_idx on bpe_chat_action_proposals (conversation_id, created_at desc);
alter table bpe_chat_conversations enable row level security;
alter table bpe_chat_messages enable row level security;
alter table bpe_chat_action_proposals enable row level security;
